<?php

namespace App\Console\Commands;

use App\Config\GoldedConfigParser;
use Illuminate\Console\Command;

class ImportGoldedConfig extends Command
{
    protected $signature = 'golded:config {path? : Path to GOLDED.CFG (defaults to ../archive/config/GOLDED.CFG)}';

    protected $description = 'Parse GOLDED.CFG and write config/golded.php';

    public function handle(): int
    {
        $path = $this->argument('path') ?? base_path('../archive/config/GOLDED.CFG');

        if (! file_exists($path)) {
            $this->error("Config file not found: {$path}");

            return self::FAILURE;
        }

        $config = (new GoldedConfigParser)->parse($path);

        $output = base_path('config/golded.php');

        file_put_contents($output, $this->render($config));

        $this->info("Written: {$output}");

        return self::SUCCESS;
    }

    private function render(array $config): string
    {
        $username = var_export($config['username'], true);
        $address = var_export($config['address'], true);
        $charsetImport = var_export($config['charset_import'], true);
        $tearline = var_export($config['tearline'], true);
        $origins = $this->renderArray($config['origins']);
        $taglines = $this->renderArray($config['taglines']);

        return <<<PHP
        <?php

        // Auto-generated by `php artisan golded:config` — do not edit by hand.
        // Re-run the command to refresh from GOLDED.CFG.

        return [
            'username'       => {$username},
            'address'        => {$address},
            'charset_import' => {$charsetImport},
            'tearline'       => {$tearline},
            'origins'        => {$origins},
            'taglines'       => {$taglines},
        ];
        PHP;
    }

    private function renderArray(array $items): string
    {
        if (empty($items)) {
            return '[]';
        }

        $lines = array_map(fn ($v) => '        '.var_export($v, true).',', $items);

        return "[\n".implode("\n", $lines)."\n    ]";
    }
}
