<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Config\GoldedConfigParser;
use Illuminate\Console\Command;

class ImportGoldedConfig extends Command
{
    protected $signature = 'golded:config {path? : Path to GOLDED.CFG (defaults to ../archive/config/GOLDED.CFG)}';

    protected $description = 'Parse GOLDED.CFG and write config/golded.php';

    public function handle(): int
    {
        $path = $this->argument('path') ?? base_path('../archive/config/GOLDED.CFG');

        if (! file_exists($path)) {
            $this->error("Config file not found: {$path}");

            return self::FAILURE;
        }

        $config = (new GoldedConfigParser)->parse($path);

        $output = base_path('config/golded.php');

        file_put_contents($output, $this->render($config));

        $this->info("Written: {$output}");

        return self::SUCCESS;
    }

    private function render(array $config): string
    {
        $username = var_export($config['username'], true);
        $address = var_export($config['address'], true);
        $charsetImport = var_export($config['charset_import'], true);
        $tearline = var_export($config['tearline'], true);
        $origins = $this->renderArray($config['origins']);
        $taglines = $this->renderArray($config['taglines']);
        $arealistsort = var_export($config['arealistsort'], true);
        $areasep = $this->renderAreasep($config['areasep']);
        $areas = $this->renderAreas($config['areas']);

        return <<<PHP
        <?php

        // Auto-generated by `php artisan golded:config` — do not edit by hand.
        // Re-run the command to refresh from GOLDED.CFG.

        return [
            'version'        => 'GoldED 7',
            'username'       => {$username},
            'address'        => {$address},
            'charset_import' => {$charsetImport},
            'tearline'       => {$tearline},
            'origins'        => {$origins},
            'taglines'       => {$taglines},
            'arealistsort'   => {$arealistsort},
            'areasep'        => {$areasep},
            'areas'          => {$areas},
        ];
        PHP;
    }

    private function renderArray(array $items): string
    {
        if ($items === []) {
            return '[]';
        }

        $lines = array_map(fn ($v): string => '        '.var_export($v, true).',', $items);

        return "[\n".implode("\n", $lines)."\n    ]";
    }

    private function renderAreasep(array $items): string
    {
        if ($items === []) {
            return '[]';
        }

        $lines = array_map(function (array $sep): string {
            $label = var_export($sep['label'], true);
            $type = var_export($sep['area_type'], true);

            return "        ['label' => {$label}, 'area_type' => {$type}],";
        }, $items);

        return "[\n".implode("\n", $lines)."\n    ]";
    }

    private function renderAreas(array $areas): string
    {
        if ($areas === []) {
            return '[]';
        }

        $lines = [];
        foreach ($areas as $path => $def) {
            $key = var_export($path, true);
            $echoid = var_export($def['echoid'], true);
            $description = var_export($def['description'], true);
            $groupId = var_export($def['group_id'], true);
            $areaType = var_export($def['area_type'], true);
            $format = var_export($def['format'], true);
            $lines[] = "        {$key} => ['echoid' => {$echoid}, 'description' => {$description}, 'group_id' => {$groupId}, 'area_type' => {$areaType}, 'format' => {$format}],";
        }

        return "[\n".implode("\n", $lines)."\n    ]";
    }
}
