<?php

// Auto-generated by `php artisan golded:config` â€” do not edit by hand.
// Re-run the command to refresh from GOLDED.CFG.

return [
    'username'       => 'Odinn Sorensen',
    'address'        => '2:236/77',
    'charset_import' => 'CP850',
    'tearline'       => '@longpid @version',
    'origins'        => [
        'http://www.goldware.dk * e-mail: odinn@goldware.dk',
        'Living in interesting times',
        'The Golden Wizard is back',
        'The Goldware BBS. #1:45821325/HST/V32B, #2:45829094/2400',
        'The Goldware BBS #1 * +45-45821325 * HST/V32B',
        'DK-BBS * DK-POINT * GOLDED * HST/V32B/V42B',
        'The Golden Wizard * GoldED Author',
        'The Golden Wizard * Just testing..',
        'Golden Wizard * GoldED Author * +45-45-821325 * HST/DS',
        'Busier than a one-legged man in an ass-kicking contest',
        '    ---> The Golden Wizard <---    ',
        ' °±² The Golden Wizard BBS * +45-45-821325 ²±° ',
        'Jeg vil godt have et semikolon her -> ;',
        '12345678901234567890123456789012345678901234567890123456789012345678901234567890',
        'dfname = @dfname, tfname = @tfname',
    ],
    'taglines'       => [],
];